{ pkgs, ... }:
{
  programs.librewolf = {
    enable = true;

    policies = {
      DisableFirefoxStudies = true;
      DisablePocket = true;
      DisableTelemetry = true;
      DontCheckDefaultBrowser = true;
      HttpsOnlyMode = "force_enabled";
      OfferToSaveLogins = false;
      PasswordManagerEnabled = false;

      # LibreWolf clears cookies and site data on shutdown. Firefox permissions
      # are origin-scoped, so retain only the HTTPS login and application
      # origins that need durable sessions.
      Cookies = {
        Allow = [
          # Development
          "https://github.com"

          # Google account and selected Google applications
          "https://google.com"
          "https://accounts.google.com"
          "https://drive.google.com"
          "https://gemini.google.com"
          "https://www.google.com"
          "https://youtube.com"
          "https://www.youtube.com"

          # Proton account and applications
          "https://account.proton.me"
          "https://calendar.proton.me"
          "https://drive.proton.me"
          "https://mail.proton.me"
          "https://pass.proton.me"

          # Tuta
          "https://app.tuta.com"

          # AI services
          "https://auth.openai.com"
          "https://chatgpt.com"
          "https://platform.openai.com"
          "https://claude.ai"

          # Social applications
          "https://x.com"
        ];
        Behavior = "reject-tracker-and-partition-foreign";
        BehaviorPrivateBrowsing = "reject-tracker-and-partition-foreign";
        Locked = false;
      };

      # Firefox history cannot be retained selectively by origin. Normal
      # windows keep history; use a private window for activity not to retain.
      SanitizeOnShutdown = {
        Cache = true;
        Cookies = true;
        FormData = true;
        History = false;
        Sessions = false;
        SiteSettings = false;
        Locked = false;
      };

      ExtensionSettings."keepassxc-browser@keepassxc.org" = {
        installation_mode = "normal_installed";
        install_url = "https://addons.mozilla.org/firefox/downloads/latest/keepassxc-browser@keepassxc.org/latest.xpi";
        default_area = "navbar";
        private_browsing = false;
      };
    };
  };

  # LibreWolf 152 uses the new XDG profile layout. Home Manager's current
  # LibreWolf profile options still target ~/.librewolf, which would create a
  # second, unused profile. Put global overrides in LibreWolf's active XDG
  # location instead; these apply to the existing and future profiles.
  xdg.configFile."librewolf/librewolf/librewolf.overrides.cfg".text = ''
    // Generated by Home Manager.
    defaultPref("browser.safebrowsing.downloads.enabled", true);
    defaultPref("browser.safebrowsing.malware.enabled", true);
    defaultPref("browser.safebrowsing.phishing.enabled", true);
    defaultPref("browser.sessionstore.resume_from_crash", true);
    defaultPref("signon.rememberSignons", false);
  '';
}
