[audio]
enable_sounds = true
sound_volume = 1.0

[backdrop]
blur_intensity = 0.20000000000000001
enabled = true
tint_intensity = 0.40000000000000002

[bar.default]
background_opacity = 0.80000000000000004
capsule_foreground = "secondary"
capsule_thickness = 0.74999998696148396
center = [ "notifications", "clock", "workspaces" ]
contact_shadow = true
end = [ "audio_visualizer", "media", "bluetooth", "brightness", "control-center", "volume", "network", "session" ]
font_family = "GeistMono Nerd Font Mono"
margin_ends = 0
padding = 15
panel_overlap = 2
position = "left"
radius = 80
radius_bottom_left = 0
radius_bottom_right = 80
radius_top_left = 0
radius_top_right = 80
scale = 1.2500000111758709
start = [ "battery", "launcher", "wallpaper", "wallhaven", "clipboard", "tray", "animetracker" ]
thickness = 40
widget_spacing = 10

[battery]
warning_threshold = 20

[control_center]
width = 900

[desktop_widgets]
enabled = true
schema_version = 2
widget_order = [ "desktop-widget-0000000000000001", "desktop-widget-0000000000000002", "desktop-widget-0000000000000003" ]

    [desktop_widgets.grid]
    cell_size = 32
    major_interval = 4
    visible = true

    [desktop_widgets.widget.desktop-widget-0000000000000001]
    box_height = 192.0
    box_width = 224.0
    cx = 144.0
    cy = 130.0
    output = "eDP-2"
    rotation = 0.0
    type = "fancy_audio_visualizer"

        [desktop_widgets.widget.desktop-widget-0000000000000001.settings]
        background = false
        bar_width = 0.20000000000000001
        bloom_intensity = 1.0
        fade_when_idle = true
        inner_diameter = 0.5
        ring_opacity = 1.0
        rotation_speed = 0.5
        sensitivity = 1.3
        visualization_mode = "all"
        wave_thickness = 1.0

    [desktop_widgets.widget.desktop-widget-0000000000000002]
    box_height = 0.0
    box_width = 0.0
    cx = 1303.0
    cy = 834.0
    output = "eDP-1"
    rotation = 0.0
    type = "clock"

        [desktop_widgets.widget.desktop-widget-0000000000000002.settings]
        background = false
        center_text = true
        clock_style = "digital"
        shadow = true

    [desktop_widgets.widget.desktop-widget-0000000000000003]
    box_height = 0.0
    box_width = 0.0
    cx = 1406.0
    cy = 34.0
    output = "eDP-1"
    rotation = 0.0
    type = "button"

        [desktop_widgets.widget.desktop-widget-0000000000000003.settings]
        background = true
        command = "noctalia msg wallpaper-random"
        glyph = "arrows-random"
        label = ""
        variant = "default"

[dock]
active_scale = 0.90000001341104507
auto_hide = true
cross_axis_padding = 2
enabled = true
inactive_opacity = 0.69999998435378075
inactive_scale = 0.80000001192092896
item_spacing = 0
launcher_position = "end"
magnification_scale = 1.2500000037252903
main_axis_padding = 6
margin_edge = 10
pinned = [ "zed", "librewolf", "org.gnome.Nautilus" ]
radius = 31
reserve_space = false
show_dots = true

[hot_corners]
enabled = true

    [hot_corners.bottom_left]
    action = "launcher"

    [hot_corners.bottom_right]
    action = "control_center"
    command = "ghostty"

    [hot_corners.top_left]
    action = "command"
    command = "noctalia msg wallpaper-random"

    [hot_corners.top_right]
    action = "window_switcher"

[idle]
behavior_order = [ "lock", "screen-off", "lock-and-suspend" ]

    [idle.behavior.lock]
    action = "lock"
    enabled = true
    timeout = 600.0

    [idle.behavior.lock-and-suspend]
    action = "lock_and_suspend"
    enabled = true
    timeout = 900.0

    [idle.behavior.screen-off]
    action = "screen_off"
    enabled = true
    timeout = 660.0

[location]
address = "Homs, Syria"

[lockscreen]
blurred_desktop = true
enabled = true

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1", "lockscreen-login-box@eDP-2" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 70.0
    box_width = 400.0
    cx = 720.0
    cy = 781.0
    output = "eDP-1"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-2"]
    box_height = 70.0
    box_width = 400.0
    cx = 720.0
    cy = 781.0
    output = "eDP-2"
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-2".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        input_opacity = 1.0
        input_radius = 6.0
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_password_hint = true

[nightlight]
enabled = true
force = true
temperature_day = 5000
temperature_night = 2500

[osd]
background_opacity = 0.89999997988343239
position = "bottom_center"
position_vertical = "bottom_right"

[plugin_settings."HotZi/anilistTracker"]
anilistPanel_placement = "attached"
anilistPanel_position = "center"

[plugin_settings."noctalia/wallhaven"]
api_key = "@WALLHAVEN_API_KEY@"
browser_placement = "attached"
download_dir = "~/Downloads"

[plugins]
enabled = [ "noctalia/wallhaven" ]

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/official-plugins"
    name = "official"

    [[plugins.source]]
    kind = "git"
    location = "https://github.com/noctalia-dev/community-plugins"
    name = "community"

[shell]
avatar_path = "/home/aqua/Pictures/profile.jpg"
corner_radius_scale = 1.4000000208616257
launch_apps_as_systemd_services = true
niri_overview_type_to_launch_enabled = true
password_style = "random"
screen_time_enabled = true
ui_scale = 1.1500000096857548

    [shell.animation]
    speed = 2.0000000298023224

    [shell.launcher]
    app_grid = false

    [shell.panel]
    clipboard_placement = "attached"
    launcher_placement = "attached"
    polkit_placement = "attached"
    session_placement = "floating"
    session_position = "bottom_center"
    transparency_mode = "glass"

    [shell.screen_corners]
    enabled = true
    size = 20

    [shell.screenshot]
    directory = "/home/aqua/Pictures/Screenshots"

    [shell.shadow]
    alpha = 0.99999997764825821
    direction = "center"

[theme]
builtin = "Catppuccin"
community_palette = "Oxocarbon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-tonal-spot"

    [theme.templates]
    builtin_ids = [ "gtk3", "gtk4", "ghostty", "niri" ]
    community_ids = [ "zed" ]

[wallpaper]
enabled = true
fill_color = "primary"
transition_on_startup = true

    [wallpaper.automation]
    enabled = true
    interval_seconds = 500
    recursive = false

    [wallpaper.default]
    path = "/home/aqua/Pictures/Wallpapers/NixOS - NIER.png"

    [wallpaper.last]
    path = "/home/aqua/Pictures/Wallpapers/NixOS - NIER.png"

    [wallpaper.monitors.eDP-1]
    path = "/home/aqua/Pictures/Wallpapers/NixOS - NIER.png"

    [wallpaper.monitors.eDP-2]
    path = "/home/aqua/Pictures/Wallpapers/wallhaven-5ymjz9.png"

[widget.animetracker]
anilist_token = "@ANILIST_TOKEN@"
capsule_radius = "auto"
enabled = true
type = "HotZi/anilistTracker:animetracker"

[widget.audio_visualizer]
bands = 20
width = 60

[widget.battery]
display_mode = "graphic"
scale = 0.90000000000000013

[widget.bluetooth]
hide_when_no_connected_device = true

[widget.brightness]
show_label = false

[widget.control-center]
enabled = false

[widget.launcher]
capsule_padding = 4
capsule_radius = 70

[widget.media]
anchor = false
hide_when_no_media = true
title_scroll = "on_hover"

[widget.network]
show_label = false

[widget.notifications]
hide_when_no_unread = true

[widget.session]
capsule = true
custom_image = "/home/aqua/Pictures/nixos.png"
custom_image_colorize = true
scale = 0.85000000000000009

[widget.tray]
enabled = true

[widget.volume]
show_label = false

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.workspaces]
anchor = true
capsule = true
minimal = true
